// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenshyuuNihongoApi.Data;

#nullable disable

namespace RenshyuuNihongoApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260909035056_StaticSeedData")]
    partial class StaticSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanjiVocabulary", b =>
                {
                    b.Property<Guid>("KanjisId")
                        .HasColumnType("uuid")
                        .HasColumnName("kanjis_id");

                    b.Property<Guid>("VocabulariesId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabularies_id");

                    b.HasKey("KanjisId", "VocabulariesId")
                        .HasName("pk_kanji_vocabulary");

                    b.HasIndex("VocabulariesId")
                        .HasDatabaseName("ix_kanji_vocabulary_vocabularies_id");

                    b.ToTable("kanji_vocabulary", (string)null);
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Example", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("GrammarId")
                        .HasColumnType("uuid")
                        .HasColumnName("grammar_id");

                    b.Property<Guid>("KanjiId")
                        .HasColumnType("uuid")
                        .HasColumnName("kanji_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VocabularyId")
                        .HasColumnType("uuid")
                        .HasColumnName("vocabulary_id");

                    b.HasKey("Id")
                        .HasName("pk_examples");

                    b.HasIndex("GrammarId")
                        .HasDatabaseName("ix_examples_grammar_id");

                    b.HasIndex("KanjiId")
                        .HasDatabaseName("ix_examples_kanji_id");

                    b.HasIndex("VocabularyId")
                        .HasDatabaseName("ix_examples_vocabulary_id");

                    b.ToTable("examples", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666661"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Đây là tôi.",
                            GrammarId = new Guid("44444444-4444-4444-4444-444444444441"),
                            KanjiId = new Guid("55555555-5555-5555-5555-555555555551"),
                            Title = "これは私です。",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            VocabularyId = new Guid("22222222-2222-2222-2222-222222222221")
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Grammar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Explanation")
                        .HasColumnType("text")
                        .HasColumnName("explanation");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.PrimitiveCollection<List<string>>("Notes")
                        .HasColumnType("text[]")
                        .HasColumnName("notes");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("structure");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_grammars");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_grammars_lesson_id");

                    b.ToTable("grammars", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444441"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Explanation = "Dùng để giới thiệu hoặc mô tả danh tính, trạng thái.",
                            LessonId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Level = 5,
                            Meaning = "Là...",
                            Notes = new List<string> { "Danh từ đứng trước は là chủ đề." },
                            Pattern = "〜です",
                            Structure = "N は N です",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Kanji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("character");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kana")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kana");

                    b.Property<string>("Kunyomi")
                        .HasColumnType("text")
                        .HasColumnName("kunyomi");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Onyomi")
                        .HasColumnType("text")
                        .HasColumnName("onyomi");

                    b.Property<int?>("StrokeCount")
                        .HasColumnType("integer")
                        .HasColumnName("stroke_count");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_kanjis");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("ix_kanjis_lesson_id");

                    b.ToTable("kanjis", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555551"),
                            Character = "日",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kana = "ひ",
                            Kunyomi = "ひ、か",
                            LessonId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Level = 5,
                            Meaning = "Ngày, mặt trời",
                            Onyomi = "ニチ",
                            StrokeCount = 4,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_number");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id")
                        .HasName("pk_lessons");

                    b.HasIndex("LessonNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_lessons_lesson_number");

                    b.HasIndex("Level")
                        .HasDatabaseName("ix_lessons_level");

                    b.HasIndex("Source")
                        .HasDatabaseName("ix_lessons_source");

                    b.ToTable("lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            LessonNumber = 1,
                            Level = "N5",
                            Source = "Minna no Nihongo",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.MockTest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_mock_tests");

                    b.ToTable("mock_tests", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777771"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Level = 5,
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Answers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("answers");

                    b.Property<string>("CorrectAnswer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correct_answer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("MockTestId")
                        .HasColumnType("uuid")
                        .HasColumnName("mock_test_id");

                    b.Property<int>("Section")
                        .HasColumnType("integer")
                        .HasColumnName("section");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_questions");

                    b.HasIndex("MockTestId")
                        .HasDatabaseName("ix_questions_mock_test_id");

                    b.ToTable("questions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888881"),
                            Answers = new List<string> { "わたし", "あなた", "たべる", "にち" },
                            CorrectAnswer = "わたし",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            MockTestId = new Guid("77777777-7777-7777-7777-777777777771"),
                            Section = 0,
                            Text = "「私」の読み方は何ですか。",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333331"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "demo@renshyuu.local",
                            Name = "Demo User",
                            Password = "$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Username = "demo"
                        });
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Vocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Kana")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("kana");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Romaji")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("romaji");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("word");

                    b.Property<string>("WordType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_type");

                    b.HasKey("Id")
                        .HasName("pk_vocabularies");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("IX_vocabulary_lesson_id");

                    b.ToTable("vocabularies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222221"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kana = "わたし",
                            LessonId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Level = "N5",
                            Meaning = "Tôi",
                            Romaji = "watashi",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Word = "私",
                            WordType = "PRONOUN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kana = "あなた",
                            LessonId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Level = "N5",
                            Meaning = "Bạn",
                            Romaji = "anata",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Word = "あなた",
                            WordType = "PRONOUN"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222223"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Kana = "たべる",
                            LessonId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Level = "N5",
                            Meaning = "Ăn",
                            Romaji = "taberu",
                            UpdatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Word = "食べる",
                            WordType = "VERB"
                        });
                });

            modelBuilder.Entity("KanjiVocabulary", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Kanji", null)
                        .WithMany()
                        .HasForeignKey("KanjisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kanji_vocabulary_kanjis_kanjis_id");

                    b.HasOne("RenshyuuNihongoApi.Models.Vocabulary", null)
                        .WithMany()
                        .HasForeignKey("VocabulariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kanji_vocabulary_vocabularies_vocabularies_id");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Example", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Grammar", "Grammar")
                        .WithMany("Examples")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_examples_grammars_grammar_id");

                    b.HasOne("RenshyuuNihongoApi.Models.Kanji", "Kanji")
                        .WithMany("Examples")
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_examples_kanjis_kanji_id");

                    b.HasOne("RenshyuuNihongoApi.Models.Vocabulary", "Vocabulary")
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_examples_vocabularies_vocabulary_id");

                    b.Navigation("Grammar");

                    b.Navigation("Kanji");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Grammar", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Lesson", "Lesson")
                        .WithMany("Grammars")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_grammars_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Kanji", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Lesson", "Lesson")
                        .WithMany("Kanjis")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_kanjis_lessons_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Question", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.MockTest", "MockTest")
                        .WithMany("Questions")
                        .HasForeignKey("MockTestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_questions_mock_tests_mock_test_id");

                    b.Navigation("MockTest");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Vocabulary", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Lesson", "Lesson")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_vocabulary_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Grammar", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Kanji", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Lesson", b =>
                {
                    b.Navigation("Grammars");

                    b.Navigation("Kanjis");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.MockTest", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Vocabulary", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
