// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RenshyuuNihongoApi.Data;

#nullable disable

namespace RenshyuuNihongoApi.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KanjiVocabulary", b =>
                {
                    b.Property<Guid>("KanjisId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VocabulariesId")
                        .HasColumnType("uuid");

                    b.HasKey("KanjisId", "VocabulariesId");

                    b.HasIndex("VocabulariesId");

                    b.ToTable("KanjiVocabulary");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Example", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GrammarId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("KanjiId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VocabularyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GrammarId");

                    b.HasIndex("KanjiId");

                    b.HasIndex("VocabularyId");

                    b.ToTable("Examples");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Grammar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Explanation")
                        .HasColumnType("text");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Structure")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Grammars");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Kanji", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Kana")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kunyomi")
                        .HasColumnType("text");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Onyomi")
                        .HasColumnType("text");

                    b.Property<int?>("StrokeCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("Kanjis");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("integer")
                        .HasColumnName("lesson_number");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Source")
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("LessonNumber")
                        .IsUnique();

                    b.HasIndex("Level");

                    b.HasIndex("Source");

                    b.ToTable("lesson", (string)null);
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Vocabulary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Kana")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("kana");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uuid")
                        .HasColumnName("lesson_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Meaning")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("meaning");

                    b.Property<string>("Romaji")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("romaji");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Word")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("word");

                    b.Property<string>("WordType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("word_type");

                    b.HasKey("Id");

                    b.HasIndex("LessonId")
                        .HasDatabaseName("IX_vocabulary_lesson_id");

                    b.ToTable("vocabulary", (string)null);
                });

            modelBuilder.Entity("KanjiVocabulary", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Kanji", null)
                        .WithMany()
                        .HasForeignKey("KanjisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenshyuuNihongoApi.Models.Vocabulary", null)
                        .WithMany()
                        .HasForeignKey("VocabulariesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Example", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Grammar", "Grammar")
                        .WithMany("Examples")
                        .HasForeignKey("GrammarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenshyuuNihongoApi.Models.Kanji", "Kanji")
                        .WithMany("Examples")
                        .HasForeignKey("KanjiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RenshyuuNihongoApi.Models.Vocabulary", "Vocabulary")
                        .WithMany("Examples")
                        .HasForeignKey("VocabularyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grammar");

                    b.Navigation("Kanji");

                    b.Navigation("Vocabulary");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Grammar", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Lesson", "Lesson")
                        .WithMany("Grammars")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Kanji", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Lesson", "Lesson")
                        .WithMany("Kanjis")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Vocabulary", b =>
                {
                    b.HasOne("RenshyuuNihongoApi.Models.Lesson", "Lesson")
                        .WithMany("Vocabularies")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("FK_vocabulary_lesson_id");

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Grammar", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Kanji", b =>
                {
                    b.Navigation("Examples");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Lesson", b =>
                {
                    b.Navigation("Grammars");

                    b.Navigation("Kanjis");

                    b.Navigation("Vocabularies");
                });

            modelBuilder.Entity("RenshyuuNihongoApi.Models.Vocabulary", b =>
                {
                    b.Navigation("Examples");
                });
#pragma warning restore 612, 618
        }
    }
}
